#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#include "stack_err_handle.h"

#define CASE_ENUM_TO_STRING(error) case error: return #error

const char* stack_error_str(stack_err_t error) {
    switch(error) {
        CASE_ENUM_TO_STRING(STACK_ERR_SUCCESS);
        CASE_ENUM_TO_STRING(STACK_ERR_DUMP_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_ALLOCATION_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_FILE_READING_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_FILE_OPEN_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_FILE_PRINT_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_NULL_PTR_ERROR);
        CASE_ENUM_TO_STRING(STACK_ERR_FILE_CLOSE_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_STR_PRINT_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_INSERTION_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_INPUT_FILE_INCORRECT);
        CASE_ENUM_TO_STRING(STACK_ERR_FILL_NODE_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_INPUT_SCAN_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_TOO_FEW_COMMAND_LINE_ARGUMENTS);
        CASE_ENUM_TO_STRING(STACK_ERR_UNKNOWN_ERROR);
        CASE_ENUM_TO_STRING(STACK_ERR_INCORRECT_STATUS);
        CASE_ENUM_TO_STRING(STACK_ERR_INCORRECT_CELL_SIZE);
        CASE_ENUM_TO_STRING(STACK_ERR_TOO_SMALL_CAPACITY);
        CASE_ENUM_TO_STRING(STACK_ERR_STK_REALLOC_FAILED);
        CASE_ENUM_TO_STRING(STACK_ERR_STK_OVERFLOW_ERROR);
        CASE_ENUM_TO_STRING(STACK_ERR_STK_IS_TOO_BIG);
        CASE_ENUM_TO_STRING(STACK_ERR_NOWHERE_TO_EXPAND);
        CASE_ENUM_TO_STRING(STACK_ERR_INVALID_STRUCT);
        CASE_ENUM_TO_STRING(STACK_ERR_DATA_CANARIES_ARE_CORRUPTED);
        CASE_ENUM_TO_STRING(STACK_ERR_STRUCT_CANARIES_ARE_CORRUPTED);
        CASE_ENUM_TO_STRING(STACK_ERR_ALIGN_IS_BROKEN);
        CASE_ENUM_TO_STRING(STACK_ERR_STRUCT_HASH_ERROR);
        CASE_ENUM_TO_STRING(STACK_ERR_DATA_HASH_ERROR);
        default:
            return "STACK_ERR_UNKNOWN_ERROR";
        return "STACK_ERR_UNKNOWN_ERROR";
    }
}

#undef CASE_ENUM_TO_STRING